geoapify_importer.settings:
  type: config_object
  label: 'Geoapify Importer settings'
  mapping:
    api_key:
      type: string
      label: 'Geoapify API key'
    reverse_geocode_enabled:
      type: boolean
      label: 'Enable reverse-geocode address verification fallback'
